site_name: CV_19_Tetuan
theme: 'readthedocs'

extra_css: [specific.css]

markdown_extensions:
    - toc:
        permalink: "#"
        separator: "_"
nav:
- CV19_Info:
    - Viseras: 'index.md'
- CV19_Tetuan:
    - MODUS OPERANDI TETUAN: 'entrega.md'